// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARm7o03GCTxQd70jvSt9hrs6RQYYCb-GU',
    appId: '1:8130781097:web:001122f007aec047d92eb8',
    messagingSenderId: '8130781097',
    projectId: 'protofood-vijisaxe',
    authDomain: 'protofood-vijisaxe.firebaseapp.com',
    storageBucket: 'protofood-vijisaxe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiUeai9xQh5tpMcdNcU5BD_1yZqdxvV8M',
    appId: '1:8130781097:android:8a5508df39f319e1d92eb8',
    messagingSenderId: '8130781097',
    projectId: 'protofood-vijisaxe',
    storageBucket: 'protofood-vijisaxe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDPi7FQi-9Rf7hLn0Y9_Pj21Rdmm6qWaQ',
    appId: '1:8130781097:ios:07d14a321b060054d92eb8',
    messagingSenderId: '8130781097',
    projectId: 'protofood-vijisaxe',
    storageBucket: 'protofood-vijisaxe.appspot.com',
    androidClientId: '8130781097-3irjq03pn7urrnngngpu7p5hkbe4hvqd.apps.googleusercontent.com',
    iosClientId: '8130781097-ld743lmathet3jkhshptr72rqavr46am.apps.googleusercontent.com',
    iosBundleId: 'com.example.protofood',
  );
}
